### ISSUE TITLE
 NaCl & Microphone Present & Audio Capture Allowed not off

### ISSUE THREAD

**Issue by am0oma** [iridium-browser/iridium-browser#49]
these turnned on after disable media in the settings:
NaCl Enabled	Yes
Microphone Present	Yes
Audio Capture Allowed
![issue](https://cloud.githubusercontent.com/assets/2161879/10448303/31fbfd90-718c-11e5-8430-169a6c2da785.jpg)
	Yes

they were all NO
please how to return them NO again?

**Comment by theurere** [comment]
I can reproduce this using OSX 10.10.5 using iridium-browser 44.1 with extras. When starting the application and seeing these settings they are:
```
NaCl Enabled	No
Microphone Present	No
Audio Capture Allowed	Yes
```
Then when I enable:
`[x] Do not allow sites to access your camera and microphone` 

these change to:
```
NaCl Enabled	Yes
Microphone Present	Yes
Audio Capture Allowed	Yes
```

When I restart the browser the setttings are back to:
```
NaCl Enabled	No
Microphone Present	No
Audio Capture Allowed	Yes
```

**Comment by theurere** [comment]
As far as privacy concerns with [hotwords](https://support.google.com/websearch/answer/2940021?p=ui_voice_search&rd=2), as you can see from the screenshot the module is not installed. Otherwise you would see all information under `Extension id` and `Module id` filled out with corresponding paths to the modules on your system.

**Comment by am0oma** [comment]
I tried what you told me yup you are right.
Thank you very much
