### ISSUE TITLE
Installation instructions don't work for Linux Mint

### ISSUE THREAD

**Issue by blyxxyz** [iridium-browser/iridium-browser#56]
I've helped a lot of people who tried to install Iridium on Linux Mint (or sometimes Debian) but failed because the official Ubuntu instructions at https://iridiumbrowser.de/download add a repository for their release name, instead of for an Ubuntu version that the repository provides. Telling them to add `deb https://downloads.iridiumbrowser.de/ubuntu utopic main` to `/etc/apt/sources.list` always solves it.

It's a fairly simple problem, but it drives away a lot of users.

Could you add support for Linux Mint release names to the repository, or publish separate instructions for Linux Mint?

**Comment by jengelh** [comment]
If it happens to work for you, that is good to hear.
However, using "foreign" packages from a different distribution is not something that is explicitly supported, because library SONAMEs, filesystem paths, and so on, may be different between various distributions/flavors.
To retain awareness of this issue, I think that using "ubuntu utopic main" over "mint something main" in source.lists is the better pick.
The ultimate goal is for distributions to adopt it themselves (see also: issue #57 ).

**Comment by blyxxyz** [comment]
It's not a good solution for Debian, but it should be fine for Mint, as long as the Ubuntu release that corresponds to the Mint release is used.

Mint's own sources.list file mostly uses upstream Ubuntu repositories. It does add a few Mint-only repositories.

My telling people to use the Utopic repository was arbitrary and might give issues, but telling them to use, for example, Trusty for Mint 17 shouldn't cause problems because Mint 17 uses a lot of packages from Trusty repositories already.

**Comment by Enkidu70** [comment]
Had the same issue a few minutes ago...

Why not just adding a seperate installation description for Mint? This is just a few minutes of work!

Please keep in mind, Mint is one of the most popular Linux distributions for destop usage!

**Comment by Duvian** [comment]
What I did was this (please note that I am on Xubuntu 15.10 Wily):

In my terminal I added the PPA-key by doing:
`sudo add-apt-repository ppa:strukturag/iridium-unstable`
This will remedy any authentication-errors in Synaptic.

Then I opened Synaptic and added this repository:
`deb http://ppa.launchpad.net/strukturag/iridium-unstable/ubuntu wily main`

After reloading the package list you should not see any key-authentication errors for the just added PPA and you should be able to type Iridium in Synaptic and install it from there.

I find this the safest way to install this version of this browser, because when any updates (if any!!!) emerge you will be notified automatically and officially via Ubuntu Software Updater...
Also when I use
`top` in my terminal to compare Firefox with Iridium the first one averages at about 6 % CPU, whilst the latter comes in at roughly 1 % CPU usage...this makes my laptop a whole lot quieter!

Hope this helps ;-)

**Comment by macandchief** [comment]
I can confirm the following on Debian (being root):

1. Add to /etc/apt/sources.list the following line:
deb https://downloads.iridiumbrowser.de/ubuntu utopic main

2. wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -

3. apt-get update

4. apt-get install iridium-browser

Works fine.

It's great that there is also an OpenSuse repository. It'd be nice to have a separate Debian repository as well (with a short description - just in order to make it much easier for noobs). Speaking of this, one should not forget about Fedora and Arch (as noob and distro hopper I always loved such projects which thought of all the main distros: Mint, Ubuntu, Debian, Suse, Fedora, Arch).

**Comment by GeorgeSalt** [comment]
When I run` sudo apt-get update` I get the following:

> Conflicting distribution: http://downloads.iridiumbrowser.de trusty InRelease (expected trusty but got stable)
> W: Failed to fetch http://downloads.iridiumbrowser.de/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
> 

`sudo apt-get install iridium-broswer` works, but Synaptic now emits the above warning every time it checks for updates.

**Comment by souldanger** [comment]
Please use the following
wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/iridium-browser.list
deb [arch=amd64] https://downloads.iridiumbrowser.de/deb/ stable main
#deb-src https://downloads.iridiumbrowser.de/deb/ stable main
EOF
sudo apt-get update
sudo apt-get install iridium-browser
