### ISSUE TITLE
Windows translation?

### ISSUE THREAD

**Issue by MichaelWeh** [iridium-browser/iridium-browser#6]
I have discovered a few pointers on Google Chrome , which have to be renamed . Similarly, the Login to Iridium , which ends on Google .
![screenshot 2](https://cloud.githubusercontent.com/assets/12396216/7567923/303725da-f800-11e4-8e05-01ce0dbd7fd3.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/12396216/7567924/303b0420-f800-11e4-901d-e35a7fb35180.png)
![screenshot 4 in iridium anmelden](https://cloud.githubusercontent.com/assets/12396216/7567925/303c5b0e-f800-11e4-82ab-5cc4afb4fd27.png)
![screenshot 1](https://cloud.githubusercontent.com/assets/12396216/7567926/303f79e2-f800-11e4-81af-fc6829ce1681.png)

**Comment by longsleep** [comment]
Thanks for the feedback. I guess we pretty much ignored Windows 8 for now. The menu entry change is now tracked at https://github.com/iridium-browser/iridium-browser-windows/issues/5

Regarding the Google login, this i not something we change. If you decide to login into your Google account with Iridium this should be possible. There is no such thing as an "Iridium account". We had a discussion if we should remove the login feature (which is currently broken) or fix it. We decided that we do not want people to decide to not use Iridium only because they want to use Google services like in Chrome.

So the issue tracked here is the "Chrome" string in "Add people to Chrome" user module.

**Comment by jengelh** [comment]
Is that actually still broken? Remember that, starting with version 43.x, all trk: requests _pass_ instead of being dropped.

**Comment by fancycode** [comment]
Yes, message strings are in `chrome/app/resources/generated_resources_XXX.xtb` (translation id `3076677906922146425`).

**Comment by jengelh** [comment]
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/diff/ui-translation-update-strings-to-read-Iridium-instea.patch?h=patchview&id=c7566afbe7ccd54d3bb218d23f48a172263e5cf0
